on: workflow_dispatch

jobs:
  record-rate:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN:${{ secrets.TEMPLATES_CLI_TOKEN }}
    steps:
      - run: |
          ratelimit=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /rate_limit )
          echo "::notice title=Current Rat Usage::${ratelimit}"
